[workspace]
resolver = "2"
members = ["franca-idl-parser", "franca-idl-parser-tests", "test-grammar-proc-macro"]

[profile.dev]
panic = "unwind"
debug = true

[profile.release]
# strip = true  # Automatically strip symbols from the binary.
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"